App\Domain\Entity\Buyer\Buyer:
    type: entity
    table: buyers
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20