App\Domain\Entity\Product\Product:
    type: entity
    table: products
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20
        price:
            type: decimal
            precision: 8
            scale: 2